name: screentime_tracker_windows
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  ffi: ^2.1.4
  fl_chart: ^1.1.0
  fluent_ui: ^4.12.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  win32: ^5.14.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
